module AppdirectIntegration
  FIELDS = [
      {name: 'company_uuid', type: :string},
      {name: 'company_name', type: :string},
      {name: 'company_email', type: :string},
      {name: 'company_phone', type: :string},
      {name: 'company_website', type: :string},
      {name: 'company_country', type: :string},
      {name: 'user_uuid', type: :string},
      {name: 'user_open_id', type: :string},
      {name: 'user_email', type: :string},
      {name: 'user_first_name', type: :string},
      {name: 'user_last_name', type: :string},
      {name: 'user_language', type: :string},
      {name: 'user_address_full_name', type: :string},
      {name: 'user_address_company_name', type: :string},
      {name: 'user_address_phone', type: :string},
      {name: 'user_address_phone_extension', type: :string},
      {name: 'user_address_fax', type: :string},
      {name: 'user_address_fax_extension', type: :string},
      {name: 'user_address_street1', type: :string},
      {name: 'user_address_street2', type: :string},
      {name: 'user_address_city', type: :string},
      {name: 'user_address_state', type: :string},
      {name: 'user_address_zip', type: :string},
      {name: 'user_address_country', type: :string},
      {name: 'user_address_pobox', type: :string},
      {name: 'user_address_pozip', type: :string},
      {name: 'status', type: :string},
      {name: 'edition', type: :string},
      {name: 'marketplace_url', type: :string},
      {name: 'pricing_duration', type: :string},
      {name: 'quantity', type: :decimal},
      {name: 'unit', type: :string},
      {name: 'quantity2', type: :decimal},
      {name: 'unit2', type: :string},
      {name: 'quantity3', type: :decimal},
      {name: 'unit3', type: :string},
      {name: 'all_data', type: :text} ]

  AR_TO_MONGOID = {
    :string => 'String',
    :decimal => 'BigDecimal',
    :timestamp => 'DateTime',
    :text => 'String'
  }
end
